### ISSUE TITLE
set [withNoContent] error

### ISSUE THREAD

**Issue by zjttfs** [MacFJA/php-redisearch#10]
## success
> $search = new \MacFJA\RediSearch\Search($client);

            $results = $search
                ->withIndex('video')
                ->withQuery('骑士')
                ->withLanguage('chinese')
                ->search();
            print_r($results);

### retrun:
![5](https://user-images.githubusercontent.com/24729880/127260601-05e38847-9a59-4613-a145-e4c0c04dec46.png)

## error
>$search = new \MacFJA\RediSearch\Search($client);
            $results = $search
                ->withIndex('video')
                ->withQuery('骑士')
                ->withLanguage('chinese')
                ->withNoContent()  //add
                ->search();

### return:
`assert(): assert(is_array($rawData)) failed`

>file : \vendor\macfja\redisearch\src\Search.php
line: 454

**Comment by MacFJA** [comment]
Hi,

Yes, this issue is the same than #9 
I will work on it this week

Thanks for the detailed report

**Comment by MacFJA** [comment]
@zjttfs Can you check is you still have the issue with `dev-master` ?
