### ISSUE TITLE
Issue in integrating php-redisearch with laravel 8

### ISSUE THREAD

**Issue by mahendran-kcube** [MacFJA/php-redisearch#18]
I have installed the plugin **MacFJA/php-redisearch** using the following command

`composer require macfja/redisearch`

And I imported as like below in laravel 

![image](https://user-images.githubusercontent.com/53893091/140014740-e5e50733-38b9-4656-9972-3bce6ff717a7.png)

and 

![image](https://user-images.githubusercontent.com/53893091/140014785-6ee011f3-f25b-4c3c-8983-ecb9d8c09d02.png)

Issue :

![image](https://user-images.githubusercontent.com/53893091/140014811-7cef3147-0035-4240-ba15-be4a1b28716f.png)

Can someone help me to resolve it

**Comment by NicoHaase** [comment]
This is also discussed on https://stackoverflow.com/questions/69820273/issue-in-integrating-php-redisearch-with-laravel-8

**Comment by MacFJA** [comment]
The `MacFJA\RediSearch\Redis\Client\ClientFacade` only exist on the `main` branch (future version 2.x of the lib, `dev-main` version in composer).

The installed version by composer (`composer require macfja/redisearch`) is at most the version 1.4.0.

----

The new version `2.x` should be available soon, I have same check to do to ensure that the lib is working correctly

**Comment by MacFJA** [comment]
BTW, thanks @NicoHaase for the answers on StackOverflow 👍
