### ISSUE TITLE
Summarize - how to switch off?

### ISSUE THREAD

**Issue by Leeloo5E** [MacFJA/php-redisearch#26]
How can I switch off the summarize option?

https://github.com/MacFJA/php-redisearch/blob/bad89b313559406957ba0d00a6cf27a9b32fc646/src/Redis/Command/Search.php#L69

see https://oss.redis.com/redisearch/Highlight/#summarization

_"RediSearch can perform summarization using the SUMMARIZE keyword. If no additional arguments are passed, all returned fields are summarized using built-in defaults."_

A workaround is actually setting  summarization to a dummy field, e.g.

`->setSummarize(['dummy'])`

**Comment by MacFJA** [comment]
It's an error.
The PR #27 will fix that.

----

With the PR #27, `SUMMARIZE` will be disabled until you call `->setSummarize(...)`

**Comment by MacFJA** [comment]
@Leeloo5E Can you try with version `dev-main#b0fcfe7766aeb4ef46dadddd564c0c33afd1c1c6` ?

If it's good for you I will make a new release

**Comment by Leeloo5E** [comment]
@MacFJA works good. Thank you very much :-)))

**Comment by pierrexp9** [comment]
Hi @MacFJA,
Can we expect this new release soon ? (I'm also a bit bothered by the forced Highlight and the forced Summarize)

**Comment by MacFJA** [comment]
I completely forgot !

I just push the new release the version **[2.1.1](https://github.com/MacFJA/php-redisearch/releases/tag/2.1.1)**
