### ISSUE TITLE
Why the null append?

### ISSUE THREAD

**Issue by spondec** [MacFJA/php-redisearch#39]
Hi,

I don't understand why appending null to the argument list when there is only one item? 

https://github.com/MacFJA/php-redisearch/blob/61eefb6cd84b17beeafc28d0b08270ea52700a16/src/Redis/Client/PhpredisClient.php#L78

A simple `FLUSHALL` command fails due to the error.

Code:
```php
$redis = new \Redis()
$redis->rawCommand('FLUSHALL'); 
````

Result: 

`OK`

Code:

```php
$clientFacade = new \MacFJA\RediSearch\Redis\Client\ClientFacade();
$client = $clientFacade->getClient($redis = new \Redis());
$client->executeRaw('FLUSHALL');
````

Result:

 ```php
  ErrorException

  Redis::rawcommand(): Raw command arguments must be scalar values!

  at vendor/macfja/redisearch/src/Redis/Client/PhpredisClient.php:81
     77▕         if (count($args) < 2) {
     78▕             $args[] = null;
     79▕         }
     80▕         // @phpstan-ignore-next-line
  ➜  81▕         return $this->redis->rawCommand(...$args);
     82▕     }
     83▕
     84▕     protected function doPipeline(Command ...$commands): array
     85▕     {
```

**Comment by MacFJA** [comment]
My bad, I was mislead by the "[PhpDoc](https://github.com/phpredis/phpredis/blob/develop/redis.stub.php#L339)" that indicate that the function need at least 2 parameters.

But [the documentation](https://github.com/phpredis/phpredis#rawcommand) ([and the code](https://github.com/phpredis/phpredis/blob/develop/redis_commands.c#L97)) indicate that only the first parameter is mandatory

I will fix it

**Comment by MacFJA** [comment]
I made a correction and publish a new version (v[2.1.2](https://github.com/MacFJA/php-redisearch/releases/tag/2.1.2))

It should be better now
