### ISSUE TITLE
why use PREFIX  with create ?

### ISSUE THREAD

**Issue by itmeicn** [MacFJA/php-redisearch#45]
FT.CREATE idx ON HASH PREFIX 1 **blog:post:** SCHEMA，PREFIX ？ how to use it create?

**Comment by MacFJA** [comment]
Hello,

You have 2 ways to set prefix(es), with the `IndexBuilder`, or with the `Create` command.

## IndexBuilder

```php
/** @var \MacFJA\RediSearch\Redis\Client $client */
$builder = (new \MacFJA\RediSearch\IndexBuilder())
    ->setIndex('idx')
    ->setPrefixes(['blog:post:']) // Setter take an array
    ->addTextField('title')
    ->addTextField('body');
$builder->create($client);
```
```php
/** @var \MacFJA\RediSearch\Redis\Client $client */
$builder = (new \MacFJA\RediSearch\IndexBuilder())
    ->setIndex('idx')
    ->addPrefixes('blog:post:') // "Adder" take one or more arguments as prefixes
    ->addTextField('title')
    ->addTextField('body');
$builder->create($client);
```

## Create

```php
/** @var \MacFJA\RediSearch\Redis\Client $client */
$create = (new \MacFJA\RediSearch\Redis\Command\Create())
   ->setIndex('idx')
   ->setPrefixes('blog:post:')
   ->addTextField('title')
   ->addTextField('body');
$client->execute($create);
```

----

I hope that answer your question.

**Comment by itmeicn** [comment]
thanks,I will. But I need more operations, such as CRUD. or detailed function description

**Comment by MacFJA** [comment]
This library is a "low-level" implementation.
It reflect operation from RediSearch as close as possible.

If you want more high level I can suggest [macfja/redisearch-integration](https://packagist.org/packages/macfja/redisearch-integration) ([git](https://github.com/MacFJA/php-redisearch-integration)).
This lib can offer method like `persist` (C and U of CRUD), `remove` (D of CRUD) and easier way to create a search (R of CRUD) on PHP object/class directly

----

But with only this library

### `C` and `U` of CRUD

`\MacFJA\RediSearch\Index::addDocumentFromArray` will be the function to use

### `R` of CRUD

`\MacFJA\RediSearch\Redis\Command\Search` will be the object to create and to use with a Client

### `D` of CRUD

You will need to use other command or use `\MacFJA\RediSearch\Redis\Client::executeRaw` (`$myClient->executeRaw('DEL', 'document_hash');`)

**Comment by itmeicn** [comment]
Thanks a lot, I will already use 2.x.
