### ISSUE TITLE
addDocumentFromArray is error,please help me

### ISSUE THREAD

**Issue by itmeicn** [MacFJA/php-redisearch#46]
```php
       $index=new \MacFJA\RediSearch\Index($this->name,$this->searchConnect);
            //dump($index);
            $res=$index->addDocumentFromArray([
                'zid'=>'553',
                'bank_number'=>'666',
                'today'=>'2022-07-21',
                'shou'=>0,
                'zhi'=>0,
                'bank_balance'=>0
            ],$this->name.':'.'553');
              echo $res;
```
is error: `assert(is_array($rawDefinitions));`
```php
    /**
     * @return null|array<string,mixed>|mixed
     */
    public function getIndexDefinition(?string $key = null)
    {
        $rawDefinitions = self::getValue($this->rawLines, 'index_definition');
        assert(is_array($rawDefinitions));
        $data = self::getPairs($rawDefinitions);
        if (!is_string($key)) {
            return $data;
        }

        return $data[$key] ?? null;
    }
```
------------------------------------------------------------
```
  -rawLines: array:48 [▼
    0 => true
    1 => true
    2 => true
    3 => []
    4 => true
    5 => array:6 [▶]
    6 => true
    7 => array:6 [▶]
    8 => true
    9 => "0"
    10 => true
    11 => "0"
    12 => true
    13 => "0"
    14 => true
    15 => "0"
    16 => true
    17 => "0"
    18 => true
    19 => "0"
    20 => true
    21 => "0"
    22 => true
    23 => "0"
    24 => true
    25 => "0"
    26 => true
    27 => "0"
    28 => true
    29 => "0"
    30 => true
    31 => "-nan"
    32 => true
    33 => "-nan"
    34 => true
    35 => "-nan"
    36 => true
    37 => "-nan"
    38 => true
    39 => "0"
    40 => true
    41 => "0"
    42 => true
    43 => "1"
    44 => true
    45 => array:14 [▶]
    46 => true
    47 => array:8 [▶]
```

**Comment by itmeicn** [comment]
$builder=new \MacFJA\RediSearch\IndexBuilder();
        $res=$builder->setIndex($this->name)->addPrefixes('finance_fun_daylog:')
            ->addTagField('zid',null,true)
            ->addTextField('bank_number',false,2,null,true,false)
            ->addTextField('today',false,2,null,true,false)
            ->addNumericField('shou')
            ->addNumericField('zhi')
            ->addNumericField('bank_balance')
            ->create($this->searchConnect);
        dump($res);//1
create index is ok

**Comment by MacFJA** [comment]
Can you dump the content of `$rawDefinitions` ?

```php
/**
     * @return null|array<string,mixed>|mixed
     */
    public function getIndexDefinition(?string $key = null)
    {
        $rawDefinitions = self::getValue($this->rawLines, 'index_definition');
        dd($rawDefinitions); // Add this line
        assert(is_array($rawDefinitions));
        $data = self::getPairs($rawDefinitions);
        if (!is_string($key)) {
            return $data;
        }

        return $data[$key] ?? null;
    }
```

**Comment by itmeicn** [comment]
$rawDefinitions = self::getValue($this->rawLines, 'index_definition');
dump($rawDefinitions);exit();
is result:null.
$a=$cacheRedis->rawCommand('ft.info','finance_fun_daylog');
dump($a);//The result is the same as the -rawLines: value,I use the open source RediSearch2.4.9. I use phpredis.

**Comment by gaohc001** [comment]
127.0.0.1:6379> module list
1) 1) "name"
   2) "ReJSON"
   3) "ver"
   4) (integer) 20008
   5) "path"
   6) "/www/server/redis/module/rejson.so"
   7) "args"
   8) (empty array)
2) 1) "name"
   2) "search"
   3) "ver"
   4) (integer) 999999
   5) "path"
   6) "/www/server/redis/module/redisearch.so"
   7) "args"
   8) (empty array)

**Comment by gaohc001** [comment]
namespace app\common\search;

use app\common\model\AdminBaseModel;
use MacFJA\RediSearch\Redis\Client\ClientFacade;
use think\facade\Cache;


class CommonSearch extends AdminBaseModel
{
    protected $name='finance_fun_daylog';//表名
    protected $searchConnect;//初始化redisearch连接
    public function __construct(array $data = [])
    {
        parent::__construct($data);
        $cacheRedis=Cache::handler();//获取连接redis句柄
        $clientFacade=new ClientFacade();
        $this->searchConnect=$clientFacade->getClient($cacheRedis);
    }
    /**
     *create indexname
     **/
    public function createIdx()
    {
        $builder=new \MacFJA\RediSearch\IndexBuilder();
        $res=$builder->setIndex($this->name)->addPrefixes('finance_fun_daylog:')
            ->addTagField('zid',null,true)
            ->addTextField('bank_number',false,2,null,true,false)
            ->addTextField('today',false,2,null,true,false)
            ->addNumericField('shou')
            ->addNumericField('zhi')
            ->addNumericField('bank_balance')
            ->create($this->searchConnect);
        dump($res);
    }
    /**
     *列表
     **/
    public function mList($h)
    {
        $search=new \MacFJA\RediSearch\Redis\Command\Search();
        $search->setIndex($this->name)
            ->setQuery('0676')
            ->setReturn('zid','bank_number');
        $result=$this->searchConnect->execute($search);
    }
    /** update data
     * @param  array $h
     **/
    public function mUpdate($h)
    {
       //先校验数据

        try {
            self::startTrans();
            //mysql表内容修改
            $res1=self::update($h);
            //redis修改内容
            $newDocument = $this->idx->makeDocument($h['id']);
            $newDocument->title->setValue($h['title']);
            $newDocument->body->setValue($h['body']);
            $newDocument->age->setValue($h['age']);
            $res2=$this->idx->replace($newDocument);
            if ($res2){
                self::commit();
                return self::JsonReturn('更新成功',200);
            }else{
                throw new \think\Exception('写入redis失败，请重试或联系技术部');
            }

        }catch (\Exception $e){
            self::rollback();
            return self::JsonReturn('错误：'.$e->getMessage(),300);
        }
    }

    /**
     *add single data
     **/
    public function mAdd($h)
    {   //先校验数据
        try {
            self::startTrans();
            //mysql添加表
           // $isId=self::insertGetId($h);
         //   if ($isId){
            $index=new \MacFJA\RediSearch\Index($this->name,$this->searchConnect);
            //dump($index);
            $res=$index->addDocumentFromArray([
                'zid'=>'553',
                'bank_number'=>'666',
                'today'=>'2022-07-21',
                'shou'=>0,
                'zhi'=>0,
                'bank_balance'=>0
            ],$this->name.':'.'553');
              echo $res;
           // }
            return self::JsonReturn('添加成功',200);
        }catch (\Exception $e){
            self::rollback();
            return self::JsonReturn('错误：'.$e->getMessage(),300);
        }
    }

    /**
     *Delete the data of the primary key Id
     **/
    public function mDel($h,$deleteDocument=false)
    {
        try {
            self::startTrans();
            if (is_array($h['id'])){
                $id=$h['id'];
            }else{
                $id=explode(",",$h['id']);
            }
            $result = self::where('id', 'in',$id)->delete();
            if ($result){
               // $index=new \MacFJA\RediSearch\Index('person',$this->searchConnect);
               // $index->
            }

        }catch (\Exception $e){
            self::rollback();
            return self::JsonReturn('错误：'.$e->getMessage(),300);
        }
    }

    /**
     *del indexname or del indexname and data
     **/
    public function mDelIndex($indexname,$deleteDocument=false)
    {
        $index=new \MacFJA\RediSearch\Index($this->name,$this->searchConnect);
        try {
            $res=$index->delete($deleteDocument);
            if ($res){
                if ($deleteDocument){
                    return self::JsonReturn('删除索引和数据成功',200);

                }else{
                    return self::JsonReturn('删除索引成功',200);
                }

            }else{
                if ($deleteDocument){
                    return self::JsonReturn('删除索引和数据失败，请重试。',300);

                }else{
                    return self::JsonReturn('删除索引失败，请重试。',300);

                }
            }
        }catch (\Exception $e){
            self::rollback();
            return self::JsonReturn('错误：'.$e->getMessage(),300);
        }

    }

    /**
     *more array data write
     **/
    public function mAddMany($h)
    {
        try {
            $documents = [];
            foreach ($h as $record) {
                // 批量添加内容且有主键id
            
            }
           
            if ($res){
                return self::JsonReturn('添加成功',200);
            }else{
                throw new \think\Exception('写入redis失败，请重试或联系技术部');
            }
        }catch (\Exception $e){
            return self::JsonReturn('错误：'.$e->getMessage(),300);
        }
    }



    /**
     *old'data write redis
     **/
    public function mysqlToRedis()
    {
        $list=self::order('id DESC')->limit(10)->select()->toArray();
        try {

            $documents = [];
            foreach ($list as $record) {
                // 批量添加内容且有主键id
         
            }
         
            if ($res){
                return self::JsonReturn('添加成功',200);
            }else{
                throw new \think\Exception('写入redis失败，请重试或联系技术部');
            }
        }catch (\Exception $e){
        return self::JsonReturn('错误：'.$e->getMessage(),300);
        }
    }

}

**Comment by itmeicn** [comment]
today,It's ok  useing old version1.4，
I use the new version 2.1.2 to work with predis1.1.10，But 2.1.2 and phpredis5.3.3 have errors. Common use of php8.0.

**Comment by MacFJA** [comment]
I see in the result of your `FT.INFO` request that all even value is equal to `true` instead of the name of the data.

So it's impossible to find the right data (even result lines are the data key, and odd result lines are the data value)

----

I can't reproduce yet your case.

----

But as a work around for now you can just call redis `HSET`:
```php
// instead of
/*
$res=$index->addDocumentFromArray([
                'zid'=>'553',
                'bank_number'=>'666',
                'today'=>'2022-07-21',
                'shou'=>0,
                'zhi'=>0,
                'bank_balance'=>0
            ],$this->name.':'.'553');
*/
// Do this
$this->searchConnect->executeRaw(
    'HSET',
    $this->name . ':' . '553',
    'zid', '553',
    'bank_number', '666',
    'today', '2022-07-21',
    'shou', 0,
    'zhi', 0,
    'bank_balance', 0
);
```
It's pretty much what do the `addDocumentFromArray`, except that `addDocumentFromArray` try to be smart and add document hash with the good prefix if you don't provide it yourself. Which is not your case

**Comment by itmeicn** [comment]
vendor/macfja/redisearch/src/Redis/Client/PhpredisClient.php
```php
    public function execute(Command $command)
    {
        $arguments = $command->getArguments();
        if (0 === count($arguments)) {
            /** @psalm-suppress TooFewArguments */
            $rawResponse = $this->redis->rawCommand($command->getId());
        } else { 
           // add line start 
            if ($command->getId()=='FT.INFO'){
                $this->redis->setOption(\Redis::OPT_REPLY_LITERAL, true); //add this line solve the problems
            }
           // add line end,ft.info can get the correct value
            $rawResponse = $this->redis->rawCommand($command->getId(), ...$arguments);
        }

        return $command->parseResponse($rawResponse);
    }
```

**Comment by itmeicn** [comment]
ths
